<?php
// +----------------------------------------------------------------------
// | park_server [ THE PROJECT NAME IS park_server ]
// +----------------------------------------------------------------------
// | FileName: ArticleTagRelation.php
// +----------------------------------------------------------------------
// | Function: 文章标签关联
// +----------------------------------------------------------------------
// | Site ( http://www.qqdeveloper.com )
// +----------------------------------------------------------------------
// | Author: 卡二条 <2665274677@qq.com>
// +----------------------------------------------------------------------
declare(strict_types=1);

namespace App\Models\Admin\Article;

use App\Scopes\WxAppId;
use Illuminate\Database\Eloquent\Model;

class ArticleTagRelation extends Model
{
    protected $table = 'article_tag_relation';
    /**
     * @var array
     */
    protected $fillable = [
        'article_uuid',
        'article_tag_uuid',
        'wxapp_id'
    ];


    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new WxAppId());
    }
}