<?php
// +----------------------------------------------------------------------
// | park_server [ THE PROJECT NAME IS park_server ]
// +----------------------------------------------------------------------
// | FileName: ArticleCategoryRelation.php
// +----------------------------------------------------------------------
// | Function: 文章分类关联
// +----------------------------------------------------------------------
// | Site ( http://www.qqdeveloper.com )
// +----------------------------------------------------------------------
// | Author: 卡二条 <2665274677@qq.com>
// +----------------------------------------------------------------------
declare(strict_types=1);

namespace App\Models\Admin\Article;

use App\Scopes\WxAppId;
use Illuminate\Database\Eloquent\Relations\Pivot;


class ArticleCategoryRelation extends Pivot
{
    /**
     * @var string
     */
    protected $table = 'article_category_relation';
    /**
     * @var array
     */
    protected $fillable = [
        'article_category_uuid',
        'article_uuid',
        'wxapp_id'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new WxAppId());
    }
}